### PR TITLE
Added function to get chrome password

### PR DESCRIPTION
**Pull request by 1Harrysmile**
add a function to get chrome password.

### CODE REVIEW

**Comment by xp4xbox** [comment]
Why did you close it

**Comment by 1Harrysmile** [comment]
I thought you wouldn’t accept it

**Comment by 1Harrysmile** [comment]
Hello any body home?

**Comment by xp4xbox** [comment]
I will look it over later, there are a few style changes that need to be done.

**Comment by 1Harrysmile** [comment]
ok

**Pull request closed without merging**
